local utils         = require("src/base/utils")
local constants     = require("src/base/constants")
local pluginbase    = require("src/plugins/pluginbase")
local bilibili      = require("src/plugins/bilibili")
local acfun         = require("src/plugins/acfun")
local application   = require("src/shell/application")

local app = application.MPVDanmakuLoaderApp:new()
local result = pluginbase.DanmakuSourceSearchResult:new()
local plugin = acfun.AcfunDanmakuSourcePlugin:new()
plugin:setApplication(app)